web/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),

    path('qunar/', include('qunar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/qunar/urls.py
from django.urls import path

from . import views, api

app_name = 'qunar'

urlpatterns = [
    path('', views.index),

    path('hotels/<str:city_name>', views.HotelList.as_view(), name='hotels'),
    path('sights/<str:city_name>', views.SightList.as_view(), name='sights'),

    path('hotel/<str:seq_no>', views.hotel_detail, name='hotel_detail'),
    path('hotel/<str:seq_no>/like', views.like_hotel, name='like_hotel'),
    path('hotel/<str:seq_no>/dislike', views.dislike_hotel, name='dislike_hotel'),

    path('sight/<int:sight_id>', views.sight_detail, name='sight_detail'),
    path('sight/<int:sight_id>/like', views.like_sight, name='like_sight'),
    path('sight/<int:sight_id>/dislike', views.dislike_sight, name='dislike_sight'),
    path('collections', views.collections, name='collections'),

    path('hot-map', views.hot_map, name='hot_map'),
    path('api/sight_points/', api.get_sight_points, name='sight_points'),
]

web/qunar/models.py
from django.contrib.auth.models import User
from django.db import models


class Province(models.Model):
    name = models.CharField(max_length=100,
                            primary_key=True)


class City(models.Model):
    name = models.CharField(max_length=100,
                            primary_key=True)
    province = models.ForeignKey(Province,
                                 on_delete=models.CASCADE,
                                 related_name='cities')


class Hotel(models.Model):
    city = models.ForeignKey(City,
                             on_delete=models.SET_NULL,
                             related_name='hotels',
                             blank=True,
                             null=True)
    seq_no = models.CharField(max_length=50,
                              primary_key=True)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    gpoint = models.CharField(max_length=100)
    dangci_text = models.CharField(max_length=20)
    dangci = models.IntegerField()
    image_url = models.CharField(max_length=1024)
    user_liked = models.ManyToManyField(User,
                                        related_name='hotels')


class HotelRatingStat(models.Model):
    hotel = models.OneToOneField(Hotel,
                                 on_delete=models.CASCADE,
                                 related_name='rating_stat')
    positive_count = models.IntegerField()
    neutral_count = models.IntegerField()
    negative_count = models.IntegerField()


class HotelComment(models.Model):
    hotel = models.ForeignKey(Hotel,
                              on_delete=models.CASCADE)
    feed_id = models.CharField(max_length=20,
                               primary_key=True)
    feed_type = models.CharField(max_length=20)
    nickname = models.CharField(max_length=100)
    content = models.TextField()


class Sight(models.Model):
    city = models.ForeignKey(City,
                             on_delete=models.SET_NULL,
                             related_name='sights',
                             blank=True,
                             null=True)
    sight_id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    score = models.FloatField(default=0.0)
    intro = models.CharField(max_length=1024)
    point = models.CharField(max_length=100)
    price = models.FloatField()
    sale_count = models.IntegerField(default=0)
    image_url = models.CharField(max_length=1024)
    users_liked = models.ManyToManyField(User,
                                         related_name='sights')

web/qunar/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView

from charts import HotelRatingPie, Top10SaleSightsBar, Top10ScoreSightsBar, \
    Top10ExpensiveHotelsBar, HotelPriceHistogram
from .models import Hotel, Sight, City
from .utils import province_cities


def index(request):
    return render(request, 'index.html')


class HotelList(ListView):
    paginate_by = 20

    def get_queryset(self):
        city_name = self.kwargs['city_name']
        if city_name == 'all':
            return Hotel.objects.order_by('seq_no')
        else:
            city = get_object_or_404(City, name=city_name)
            hotels = city.hotels.order_by('seq_no')
            return hotels

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city_name = self.kwargs['city_name']
        context['top_10_expensive_hotels_bar_url'] = \
            Top10ExpensiveHotelsBar(city_name).url
        context['hotels_price_histogram_url'] = \
            HotelPriceHistogram(city_name).url
        if city_name != 'all':
            context['city_name'] = self.kwargs['city_name']
        return context


class SightList(ListView):
    paginate_by = 20

    def get_queryset(self):
        city_name = self.kwargs['city_name']
        if city_name == 'all':
            return Sight.objects.order_by('sight_id')
        else:
            city = get_object_or_404(City, name=city_name)
            sights = city.sights.order_by('sight_id')
            return sights

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city_name = self.kwargs['city_name']
        context['top_10_sale_sights_bar_url'] = Top10SaleSightsBar(city_name).url
        context['top_10_score_sights_bar_url'] = Top10ScoreSightsBar(city_name).url
        if city_name != 'all':
            context['city_name'] = self.kwargs['city_name']
        return context


def hotel_detail(request, seq_no):
    hotel = Hotel.objects.get(seq_no=seq_no)
    rating_pie_url = HotelRatingPie(hotel.seq_no).url
    return render(request, 'hotel_detail.html',
                  {'hotel': hotel,
                   'rating_pie_url': rating_pie_url})


def sight_detail(request, sight_id):
    sight = Sight.objects.get(sight_id=sight_id)
    return render(request, 'sight_detail.html',
                  {'sight': sight})


@login_required
def collections(request):
    user = request.user
    hotels = user.hotels.all()
    sights = user.sights.all()
    return render(request, 'collections.html',
                  {'hotels': hotels,
                   'sights': sights})


@login_required
def like_hotel(request, seq_no):
    user = request.user
    hotel = get_object_or_404(Hotel, seq_no=seq_no)
    user.hotels.add(hotel)
    messages.info(request, '收藏成功~')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def dislike_hotel(request, seq_no):
    user = request.user
    hotel = get_object_or_404(Hotel, seq_no=seq_no)
    user.hotels.remove(hotel)
    messages.info(request, '取消成功')
    return redirect('qunar:collections')


@login_required
def like_sight(request, sight_id):
    user = request.user
    sight = get_object_or_404(Sight, sight_id=sight_id)
    user.sights.add(sight)
    messages.info(request, '收藏成功~')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def dislike_sight(request, sight_id):
    user = request.user
    sight = get_object_or_404(Sight, sight_id=sight_id)
    user.sights.remove(sight)
    messages.info(request, '取消成功')
    return redirect('qunar:collections')

def hot_map(request):
    return render(request, 'qunar/hot_map.html')

web/qunar/templates/collections.html
{% extends "layouts/default/page.html" %}

{% block content %}
    <h3>收藏的酒店~~~~</h3>
    <ul class="list-group">
        {% for hotel in hotels %}
            <li class="list-group-item">
                <a href="{% url 'qunar:hotel_detail' hotel.seq_no %}">{{ hotel.name }}</a>
                <a class="btn btn-danger" href="{% url 'qunar:dislike_hotel' hotel.seq_no %}">取消收藏</a>
            </li>
        {% endfor %}
    </ul>

    <h3>收藏的景点~~</h3>
    <ul class="list-group">
        {% for sight in sights %}
            <li class="list-group-item">
                <a href="{% url 'qunar:sight_detail' sight.sight_id %}">{{ sight.name }}</a>
                <a class="btn btn-danger" href="{% url 'qunar:dislike_sight' sight.sight_id %}">取消收藏</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

web/qunar/templates/hotel_detail.html
{% extends "layouts/default/page.html" %}

{% block content %}
    <div class="row">
        <div class="col">
            <img src="{{ hotel.image_url }}" class="img-fluid" alt="Responsive image">
            <table class="table">
                <tbody>
                <tr>
                    <th scope="row">酒店名字</th>
                    <td>{{ hotel.name }}</td>
                </tr>
                <tr>
                    <th scope="row">酒店价格</th>
                    <td>{{ hotel.price }}</td>
                </tr>
                <tr>
                    <th scope="row">酒店全球坐标</th>
                    <td>{{ hotel.gpoint }}</td>
                    <td>酒店档次</td>
                    <td>{{ hotel.dangci_text }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col">
            <img src="{{ rating_pie_url }}" alt="">
        </div>
    </div>


{% endblock %}

web/qunar/templates/hotels_all.html
{% extends "layouts/default/page.html" %}

{% block content %}
    <h1>所有酒店~~</h1>
    <ul class="list-group">
        {% with collections=request.user.hotels.all %}
            {% for hotel in hotels %}
                <li class="list-group-item">
                    <a href="{% url 'qunar:hotel_detail' hotel.seq_no %}">{{ hotel.name }}</a>
                    {% if hotel in collections %}
                        <a class="btn btn-success disabled" href="{% url 'qunar:like_hotel' hotel.seq_no %}">已收藏</a>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'qunar:like_hotel' hotel.seq_no %}">收藏</a>
                    {% endif %}
                </li>
            {% endfor %}
        {% endwith %}
    </ul>
{% endblock %}

web/qunar/templates/sight_detail.html
{% extends "layouts/default/page.html" %}

{% block content %}
    <img src="{{ sight.image_url }}" class="img-fluid" alt="Responsive image">
    <table class="table">
        <tbody>
        <tr>
            <th scope="row">景点名字</th>
            <td>{{ sight.name }}</td>
        </tr>
        <tr>
            <th scope="row">景点简介</th>
            <td>{{ sight.intro }}</td>
        </tr>
        <tr>
            <th scope="row">景点评分</th>
            <td>{{ sight.score }}</td>
        </tr>
        <tr>
            <th scope="row">景点全球坐标</th>
            <td>{{ sight.point }}</td>
        </tr>
        <tr>
            <td>景点价格</td>
            <td>{{ sight.price }}</td>
        </tr>
        <tr>
            <th scope="row">景点门票销量</th>
            <td>{{ sight.sale_count }}</td>
        </tr>
        </tbody>
    </table>

{% endblock %}

web/qunar/templates/sights_all.html
{% extends "layouts/default/page.html" %}

{% block content %}
    <h1>所有景点~~</h1>
    <ul class="list-group">
        {% with collections=request.user.sights.all %}
            {% for sight in sights %}
                <li class="list-group-item">
                    <a href="{% url 'qunar:sight_detail' sight.sight_id %}">{{ sight.name }}</a>
                    {% if sight in collections %}
                        <a class="btn btn-success disabled" href="{% url 'qunar:like_sight' sight.sight_id %}">已收藏</a>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'qunar:like_sight' sight.sight_id %}">收藏</a>
                    {% endif %}
                </li>
            {% endfor %}
        {% endwith %}
    </ul>
{% endblock %}