web/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),

    path('qunar/', include('qunar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/qunar/urls.py
from django.urls import path

from . import views, api

app_name = 'qunar'

urlpatterns = [
    path('', views.index),

    path('hotels/<str:city_name>', views.HotelList.as_view(), name='hotels'),
    path('sights/<str:city_name>', views.SightList.as_view(), name='sights'),

    path('hotel/<str:seq_no>', views.hotel_detail, name='hotel_detail'),
    path('hotel/<str:seq_no>/like', views.like_hotel, name='like_hotel'),
    path('hotel/<str:seq_no>/dislike', views.dislike_hotel, name='dislike_hotel'),

    path('sight/<int:sight_id>', views.sight_detail, name='sight_detail'),
    path('sight/<int:sight_id>/like', views.like_sight, name='like_sight'),
    path('sight/<int:sight_id>/dislike', views.dislike_sight, name='dislike_sight'),
    path('collections', views.collections, name='collections'),

    path('hot-map', views.hot_map, name='hot_map'),
    path('api/sight_points/', api.get_sight_points, name='sight_points'),
]

web/qunar/models.py
from django.contrib.auth.models import User
from django.db import models


class Province(models.Model):
    name = models.CharField(max_length=100,
                            primary_key=True)


class City(models.Model):
    name = models.CharField(max_length=100,
                            primary_key=True)
    province = models.ForeignKey(Province,
                                 on_delete=models.CASCADE,
                                 related_name='cities')


class Hotel(models.Model):
    city = models.ForeignKey(City,
                             on_delete=models.SET_NULL,
                             related_name='hotels',
                             blank=True,
                             null=True)
    seq_no = models.CharField(max_length=50,
                              primary_key=True)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    gpoint = models.CharField(max_length=100)
    dangci_text = models.CharField(max_length=20)
    dangci = models.IntegerField()
    image_url = models.CharField(max_length=1024)
    user_liked = models.ManyToManyField(User,
                                        related_name='hotels')


class HotelRatingStat(models.Model):
    hotel = models.OneToOneField(Hotel,
                                 on_delete=models.CASCADE,
                                 related_name='rating_stat')
    positive_count = models.IntegerField()
    neutral_count = models.IntegerField()
    negative_count = models.IntegerField()


class HotelComment(models.Model):
    hotel = models.ForeignKey(Hotel,
                              on_delete=models.CASCADE)
    feed_id = models.CharField(max_length=20,
                               primary_key=True)
    feed_type = models.CharField(max_length=20)
    nickname = models.CharField(max_length=100)
    content = models.TextField()


class Sight(models.Model):
    city = models.ForeignKey(City,
                             on_delete=models.SET_NULL,
                             related_name='sights',
                             blank=True,
                             null=True)
    sight_id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    score = models.FloatField(default=0.0)
    intro = models.CharField(max_length=1024)
    point = models.CharField(max_length=100)
    price = models.FloatField()
    sale_count = models.IntegerField(default=0)
    image_url = models.CharField(max_length=1024)
    users_liked = models.ManyToManyField(User,
                                         related_name='sights')

web/qunar/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView

from charts import HotelRatingPie, Top10SaleSightsBar, Top10ScoreSightsBar, \
    Top10ExpensiveHotelsBar, HotelPriceHistogram
from .models import Hotel, Sight, City
from .utils import province_cities


def index(request):
    return render(request, 'index.html')


class HotelList(ListView):
    paginate_by = 20

    def get_queryset(self):
        city_name = self.kwargs['city_name']
        if city_name == 'all':
            return Hotel.objects.order_by('seq_no')
        else:
            city = get_object_or_404(City, name=city_name)
            hotels = city.hotels.order_by('seq_no')
            return hotels

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city_name = self.kwargs['city_name']
        context['top_10_expensive_hotels_bar_url'] = \
            Top10ExpensiveHotelsBar(city_name).url
        context['hotels_price_histogram_url'] = \
            HotelPriceHistogram(city_name).url
        if city_name != 'all':
            context['city_name'] = self.kwargs['city_name']
        return context


class SightList(ListView):
    paginate_by = 20

    def get_queryset(self):
        city_name = self.kwargs['city_name']
        if city_name == 'all':
            return Sight.objects.order_by('sight_id')
        else:
            city = get_object_or_404(City, name=city_name)
            sights = city.sights.order_by('sight_id')
            return sights

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city_name = self.kwargs['city_name']
        context['top_10_sale_sights_bar_url'] = Top10SaleSightsBar(city_name).url
        context['top_10_score_sights_bar_url'] = Top10ScoreSightsBar(city_name).url
        if city_name != 'all':
            context['city_name'] = self.kwargs['city_name']
        return context


def hotel_detail(request, seq_no):
    hotel = Hotel.objects.get(seq_no=seq_no)
    rating_pie_url = HotelRatingPie(hotel.seq_no).url
    return render(request, 'hotel_detail.html',
                  {'hotel': hotel,
                   'rating_pie_url': rating_pie_url})


def sight_detail(request, sight_id):
    sight = Sight.objects.get(sight_id=sight_id)
    return render(request, 'sight_detail.html',
                  {'sight': sight})


@login_required
def collections(request):
    user = request.user
    hotels = user.hotels.all()
    sights = user.sights.all()
    return render(request, 'collections.html',
                  {'hotels': hotels,
                   'sights': sights})


@login_required
def like_hotel(request, seq_no):
    user = request.user
    hotel = get_object_or_404(Hotel, seq_no=seq_no)
    user.hotels.add(hotel)
    messages.info(request, '收藏成功~')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def dislike_hotel(request, seq_no):
    user = request.user
    hotel = get_object_or_404(Hotel, seq_no=seq_no)
    user.hotels.remove(hotel)
    messages.info(request, '取消成功')
    return redirect('qunar:collections')


@login_required
def like_sight(request, sight_id):
    user = request.user
    sight = get_object_or_404(Sight, sight_id=sight_id)
    user.sights.add(sight)
    messages.info(request, '收藏成功~')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def dislike_sight(request, sight_id):
    user = request.user
    sight = get_object_or_404(Sight, sight_id=sight_id)
    user.sights.remove(sight)
    messages.info(request, '取消成功')
    return redirect('qunar:collections')

def hot_map(request):
    return render(request, 'qunar/hot_map.html')

web/qunar/templates/qunar/hot_map.html
{% extends 'layouts/default/page.html' %}
{% block head %}
    {{ block.super }}
    <script type="text/javascript" src="//api.map.baidu.com/api?v=2.0&ak=bO4few1LvTkSVHHUUs0T79hxl84krh8S"></script>
    <script type="text/javascript" src="//api.map.baidu.com/library/Heatmap/2.0/src/Heatmap_min.js"></script>
    <script src="https://cdn.bootcss.com/axios/0.19.2/axios.min.js"></script>
    <title>热力图功能示例</title>
    <style type="text/css">
        ul, li {
            list-style: none;
            margin: 0;
            padding: 0;
            float: left;
        }

        html {
            height: 100%
        }

        body {
            height: 100%;
            margin: 0px;
            padding: 0px;
            font-family: "微软雅黑";
        }

        #container {
            height: 500px;
            width: 100%;
        }

        #r-result {
            width: 100%;
        }
    </style>
{% endblock %}
{% block content %}
    <div id="container"></div>
    <div id="r-result">
        <input type="button" onclick="openHeatmap();" value="显示热力图"/><input type="button" onclick="closeHeatmap();"
                                                                            value="关闭热力图"/>
    </div>
    <script type="text/javascript">
        var map = new BMap.Map("container");          // 创建地图实例

        var point = new BMap.Point(116.418261, 39.921984);
        map.centerAndZoom(point, 10);             // 初始化地图，设置中心点坐标和地图级别
        map.enableScrollWheelZoom(); // 允许滚轮缩放

        if (!isSupportCanvas()) {
            alert('热力图目前只支持有canvas支持的浏览器,您所使用的浏览器不能使用热力图功能~')
        }
        //详细的参数,可以查看heatmap.js的文档 https://github.com/pa7/heatmap.js/blob/master/README.md
        //参数说明如下:
        /* visible 热力图是否显示,默认为true
         * opacity 热力的透明度,1-100
         * radius 势力图的每个点的半径大小
         * gradient  {JSON} 热力图的渐变区间 . gradient如下所示
         *	{
                .2:'rgb(0, 255, 255)',
                .5:'rgb(0, 110, 255)',
                .8:'rgb(100, 0, 255)'
            }
            其中 key 表示插值的位置, 0~1.
                value 为颜色值.
         */
        heatmapOverlay = new BMapLib.HeatmapOverlay({"radius": 20});
        map.addOverlay(heatmapOverlay);

        axios.get('{% url 'qunar:sight_points' %}?city_name={{ request.GET.city_name }}')
            .then(function (response) {
                points = response.data
                heatmapOverlay.setDataSet({data: points, max: 100});
                if (points.length > 0) {
                    point = new BMap.Point(points[0].lng, points[0].lat);
                    {% if not request.GET.city_name %}
                        let zoomVal = 5
                    {% else %}
                        let zoomVal = 10
                    {% endif %}
                    map.centerAndZoom(point, zoomVal);             // 初始化地图，设置中心点坐标和地图级别
                }
            })

        //是否显示热力图
        function openHeatmap() {
            heatmapOverlay.show();
        }

        function closeHeatmap() {
            heatmapOverlay.hide();
        }

        {#closeHeatmap();#}

        function setGradient() {
            /*格式如下所示:
           {
                 0:'rgb(102, 255, 0)',
                 .5:'rgb(255, 170, 0)',
                 1:'rgb(255, 0, 0)'
           }*/
            var gradient = {};
            var colors = document.querySelectorAll("input[type='color']");
            colors = [].slice.call(colors, 0);
            colors.forEach(function (ele) {
                gradient[ele.getAttribute("data-key")] = ele.value;
            });
            heatmapOverlay.setOptions({"gradient": gradient});
        }

        //判断浏览区是否支持canvas
        function isSupportCanvas() {
            var elem = document.createElement('canvas');
            return !!(elem.getContext && elem.getContext('2d'));
        }
    </script>
{% endblock %}

web/qunar/templates/qunar/hotel_list.html
{% extends "layouts/default/page.html" %}

{% block content %}
    {% if city_name %}
        <h3>{{ city_name }}的酒店~~</h3>
    {% else %}
        <h3>所有酒店~~</h3>
    {% endif %}
    <div class="row">
        <div class="col">
            <ul class="list-group">
                {% with collections=request.user.hotels.all %}
                    {% for hotel in object_list %}
                        <li class="list-group-item d-flex">
                            <a class="mr-auto" href="{% url 'qunar:hotel_detail' hotel.seq_no %}">{{ hotel.name }}</a>
                            {% if hotel in collections %}
                                <a class="btn btn-success disabled"
                                   href="{% url 'qunar:like_hotel' hotel.seq_no %}">已收藏</a>
                            {% else %}
                                <a class="btn btn-primary" href="{% url 'qunar:like_hotel' hotel.seq_no %}">收藏</a>
                            {% endif %}
                        </li>
                    {% endfor %}
                {% endwith %}
            </ul>
        </div>
        <div class="col">
            <img src="{{ top_10_expensive_hotels_bar_url }}" alt="">
            <img src="{{ hotels_price_histogram_url }}" alt="">
        </div>
    </div>
    <br>
    {% include 'qunar/pagination.html' %}
{% endblock %}

web/qunar/templates/qunar/pagination.html
<nav aria-label="...">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                   tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link"
                   tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% endif %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_obj.number }}<span class="sr-only">(current)</span></a>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">Next</a>
            </li>
        {% endif %}
        <li class="page-item"><a class="page-link">共{{ page_obj.paginator.num_pages }}页</a></li>
    </ul>
</nav>

web/qunar/templates/qunar/sight_list.html
{% extends "layouts/default/page.html" %}

{% block content %}
    {% if city_name %}
        <h3>{{ city_name }}的景点 !!</h3>
    {% else %}
        <h3>所有景点~~</h3>
    {% endif %}
    <div class="row">
        <div class="col">
            <ul class="list-group list-group-flush">
                {% with collections=request.user.sights.all %}
                    {% for sight in object_list %}
                        <li class="list-group-item d-flex">
                            <a class="mr-auto" href="{% url 'qunar:sight_detail' sight.sight_id %}">{{ sight.name }}</a>
                            {% if sight in collections %}
                                <a class="btn btn-success disabled" href="{% url 'qunar:like_sight' sight.sight_id %}">已收藏</a>
                            {% else %}
                                <a class="btn btn-primary" href="{% url 'qunar:like_sight' sight.sight_id %}">收藏</a>
                            {% endif %}
                        </li>
                    {% endfor %}
                {% endwith %}
            </ul>
        </div>
        <div class="col">
            <img src="{{ top_10_sale_sights_bar_url }}" alt="">
            <img src="{{ top_10_score_sights_bar_url }}" alt="">
        </div>
    </div>
    <br>
    {% include 'qunar/pagination.html' %}
{% endblock %}