web/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

web/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),

    path('qunar/', include('qunar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/qunar/urls.py
from django.urls import path

from . import views, api

app_name = 'qunar'

urlpatterns = [
    path('', views.index),

    path('hotels/<str:city_name>', views.HotelList.as_view(), name='hotels'),
    path('sights/<str:city_name>', views.SightList.as_view(), name='sights'),

    path('hotel/<str:seq_no>', views.hotel_detail, name='hotel_detail'),
    path('hotel/<str:seq_no>/like', views.like_hotel, name='like_hotel'),
    path('hotel/<str:seq_no>/dislike', views.dislike_hotel, name='dislike_hotel'),

    path('sight/<int:sight_id>', views.sight_detail, name='sight_detail'),
    path('sight/<int:sight_id>/like', views.like_sight, name='like_sight'),
    path('sight/<int:sight_id>/dislike', views.dislike_sight, name='dislike_sight'),
    path('collections', views.collections, name='collections'),

    path('hot-map', views.hot_map, name='hot_map'),
    path('api/sight_points/', api.get_sight_points, name='sight_points'),
]

web/content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    {% block head %}

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="An example of Django project with basic user functionality.">
    <meta name="author" content="Yehor Smoliakov">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>Simple Django Login and Registration</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    {% endblock %}

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'Home' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'qunar:hotels' 'all' %}">酒店</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'qunar:sights' 'all' %}">景点</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    酒店(城市)
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {% for province, cities in province_cities.items %}
                        <li class="dropdown-submenu">
                            <a class="dropdown-item dropdown-toggle" href="#">{{ province }}</a>
                            <ul class="dropdown-menu">
                                {% for city in cities %}
                                    <li><a class="dropdown-item" href="{% url 'qunar:hotels' city %}">{{ city }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    景点(城市)
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {% for province, cities in province_cities.items %}
                        <li class="dropdown-submenu">
                            <a class="dropdown-item dropdown-toggle" href="#">{{ province }}</a>
                            <ul class="dropdown-menu">
                                {% for city in cities %}
                                    <li><a class="dropdown-item" href="{% url 'qunar:sights' city %}">{{ city }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'qunar:hot_map' %}">热力图</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    热力图(城市)
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {% for province, cities in province_cities.items %}
                        <li class="dropdown-submenu">
                            <a class="dropdown-item dropdown-toggle" href="#">{{ province }}</a>
                            <ul class="dropdown-menu">
                                {% for city in cities %}
                                    <li><a class="dropdown-item" href="{% url 'qunar:hot_map' %}?city_name={{ city }}">{{ city }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ request.user.email }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'qunar:collections' %}">个人收藏</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"
                           href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>
                        <a class="dropdown-item"
                           href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a>
                        <a class="dropdown-item"
                           href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>
                    </div>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
                </li>
            {% endif %}
        </ul>

    </div>

</nav>

<div class="container-fluid mt-3">

    {% bootstrap_messages %}

    {% block content %}
        No content.
    {% endblock %}

</div>

<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

<script src="{% static 'js/drop_down.js' %}"></script>

</body>
</html>